### ISSUE TITLE
Params redirect

### ISSUE THREAD

**Issue by robersonfaria** [Neurony/laravel-redirects#2]
Is possible redirecting routes with parameters and reorder the parameters?

Ex:
app('redirect.model')->create([
    'old_url' => '/search/users/{user}',
    'new_url => '/user/search/{user}',
    'status' => 301
]);

Or yet, transform into query param:
Ex:
app('redirect.model')->create([
    'old_url' => '/search/{term}',
    'new_url => '/search?q={user}',
    'status' => 301
]);

If not possible, are features planned for the future?

Thank you.

**Comment by zbiller** [comment]
Hi @robersonfaria 

I would suggest only storing values inside the `redirects` table and that's because of how the `RedirectsRequests` middleware works (it matches your current URL with a record inside the `redirects` table).

Storing routes with parameters might cause issues when you have something like this in your routes file:

```
Route::get('search/users/latest');
Route::get('search/users/{user}');
```

The middleware doesn't hook into your routes and naturally, if you were to have `search/users/{user}` as a redirect, it will also redirect the `latest` URL.

Nevertheless, if you really want to store parameters in your redirects, you can do so. The only thing you need to do afterwards is to replace the `RedirectsRequests` with your own middleware that will handle the redirect logic.

Thank you!
